// ============================================
// Cherry Jewelry — Sample Product Data
// Used for development before database integration
// ============================================

import type { Product, Category } from "@/types";

export const sampleCategories: Category[] = [
  {
    id: "cat-1",
    name: "Rings",
    slug: "rings",
    description: "Exquisite rings for every occasion",
    image: "/images/categories/rings.jpg",
    parentId: null,
    position: 1,
    isActive: true,
  },
  {
    id: "cat-2",
    name: "Necklaces",
    slug: "necklaces",
    description: "Stunning necklaces that captivate",
    image: "/images/categories/necklaces.jpg",
    parentId: null,
    position: 2,
    isActive: true,
  },
  {
    id: "cat-3",
    name: "Earrings",
    slug: "earrings",
    description: "Elegant earrings for every style",
    image: "/images/categories/earrings.jpg",
    parentId: null,
    position: 3,
    isActive: true,
  },
  {
    id: "cat-4",
    name: "Bracelets",
    slug: "bracelets",
    description: "Beautiful bracelets that shine",
    image: "/images/categories/bracelets.jpg",
    parentId: null,
    position: 4,
    isActive: true,
  },
  {
    id: "cat-5",
    name: "Pendants",
    slug: "pendants",
    description: "Charming pendants close to your heart",
    image: "/images/categories/pendants.jpg",
    parentId: null,
    position: 5,
    isActive: true,
  },
  {
    id: "cat-6",
    name: "Bangles",
    slug: "bangles",
    description: "Traditional bangles with modern elegance",
    image: "/images/categories/bangles.jpg",
    parentId: null,
    position: 6,
    isActive: true,
  },
];

export const sampleProducts: Product[] = [
  {
    id: "prod-1",
    name: "Celestial Diamond Ring",
    slug: "celestial-diamond-ring",
    description: "A breathtaking ring featuring a brilliant-cut diamond surrounded by a halo of smaller diamonds, set in 18K yellow rose-gold. The celestial design captures the essence of starlight, making it perfect for engagements or special celebrations.",
    shortDescription: "18K Gold brilliant-cut diamond halo ring",
    price: 45999,
    compareAtPrice: 52999,
    costPrice: 32000,
    sku: "LUM-RNG-001",
    material: "Gold (18K)",
    weight: "4.2g",
    purity: "750",
    categoryId: "cat-1",
    images: [
      { id: "img-1", url: "", alt: "Celestial Diamond Ring front", position: 0, productId: "prod-1" },
      { id: "img-2", url: "", alt: "Celestial Diamond Ring side", position: 1, productId: "prod-1" },
    ],
    variants: [
      { id: "var-1", name: "Size 6", sku: "LUM-RNG-001-6", price: 45999, compareAtPrice: 52999, material: "Gold (18K)", size: "6", weight: "4.2g", stock: 8, productId: "prod-1", isActive: true },
      { id: "var-2", name: "Size 7", sku: "LUM-RNG-001-7", price: 45999, compareAtPrice: 52999, material: "Gold (18K)", size: "7", weight: "4.5g", stock: 12, productId: "prod-1", isActive: true },
      { id: "var-3", name: "Size 8", sku: "LUM-RNG-001-8", price: 45999, compareAtPrice: 52999, material: "Gold (18K)", size: "8", weight: "4.8g", stock: 5, productId: "prod-1", isActive: true },
    ],
    reviews: [],
    tags: ["diamond", "engagement", "halo", "rose-gold"],
    metaTitle: "Celestial Diamond Ring | 18K Gold | Cherry Jewelry",
    metaDescription: "Shop the Celestial Diamond Ring — a brilliant-cut diamond halo ring set in 18K yellow rose-gold.",
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: true,
    isActive: true,
    averageRating: 4.8,
    reviewCount: 24,
    createdAt: new Date("2025-01-15"),
    updatedAt: new Date("2025-06-01"),
  },
  {
    id: "prod-2",
    name: "Aria Gold Necklace",
    slug: "aria-rose-gold-necklace",
    description: "An elegant 22K rose-gold necklace with intricate filigree work and a stunning center pendant. The Aria collection represents the melody of fine craftsmanship, with each link hand-finished to perfection.",
    shortDescription: "22K Gold filigree necklace with center pendant",
    price: 78500,
    compareAtPrice: 89999,
    costPrice: 58000,
    sku: "LUM-NCK-001",
    material: "Gold (22K)",
    weight: "18.5g",
    purity: "916",
    categoryId: "cat-2",
    images: [
      { id: "img-3", url: "", alt: "Aria Gold Necklace", position: 0, productId: "prod-2" },
    ],
    variants: [
      { id: "var-4", name: "16 inch", sku: "LUM-NCK-001-16", price: 78500, compareAtPrice: 89999, material: "Gold (22K)", size: "16 inch", weight: "18.5g", stock: 6, productId: "prod-2", isActive: true },
      { id: "var-5", name: "18 inch", sku: "LUM-NCK-001-18", price: 82500, compareAtPrice: 94999, material: "Gold (22K)", size: "18 inch", weight: "20.2g", stock: 4, productId: "prod-2", isActive: true },
    ],
    reviews: [],
    tags: ["rose-gold", "necklace", "filigree", "wedding"],
    metaTitle: null,
    metaDescription: null,
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    isActive: true,
    averageRating: 4.9,
    reviewCount: 18,
    createdAt: new Date("2025-02-10"),
    updatedAt: new Date("2025-06-01"),
  },
  {
    id: "prod-3",
    name: "Rose Petal Earrings",
    slug: "rose-petal-earrings",
    description: "Delicate rose rose-gold drop earrings inspired by blooming petals. Featuring micro-pavé diamonds that catch the light with every movement, these earrings add a touch of romantic elegance to any ensemble.",
    shortDescription: "Rose rose-gold drop earrings with micro-pavé diamonds",
    price: 28999,
    compareAtPrice: null,
    costPrice: 18500,
    sku: "LUM-EAR-001",
    material: "Rose Gold",
    weight: "6.4g",
    purity: "750",
    categoryId: "cat-3",
    images: [
      { id: "img-4", url: "", alt: "Rose Petal Earrings", position: 0, productId: "prod-3" },
    ],
    variants: [
      { id: "var-6", name: "Standard", sku: "LUM-EAR-001-STD", price: 28999, compareAtPrice: null, material: "Rose Gold", size: null, weight: "6.4g", stock: 15, productId: "prod-3", isActive: true },
    ],
    reviews: [],
    tags: ["rose rose-gold", "earrings", "diamond", "drop"],
    metaTitle: null,
    metaDescription: null,
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    isActive: true,
    averageRating: 4.7,
    reviewCount: 31,
    createdAt: new Date("2025-05-20"),
    updatedAt: new Date("2025-06-01"),
  },
  {
    id: "prod-4",
    name: "Eternal Knot Bracelet",
    slug: "eternal-knot-bracelet",
    description: "A stunning 18K white rose-gold bracelet featuring an eternal knot design, symbolizing everlasting love. Adorned with brilliant-cut diamonds, this piece is both a statement and a keepsake.",
    shortDescription: "18K White Gold eternal knot diamond bracelet",
    price: 62000,
    compareAtPrice: 72000,
    costPrice: 42000,
    sku: "LUM-BRC-001",
    material: "White Gold",
    weight: "12.8g",
    purity: "750",
    categoryId: "cat-4",
    images: [
      { id: "img-5", url: "", alt: "Eternal Knot Bracelet", position: 0, productId: "prod-4" },
    ],
    variants: [
      { id: "var-7", name: "Small (6.5\")", sku: "LUM-BRC-001-S", price: 62000, compareAtPrice: 72000, material: "White Gold", size: "6.5 inch", weight: "12.0g", stock: 7, productId: "prod-4", isActive: true },
      { id: "var-8", name: "Medium (7\")", sku: "LUM-BRC-001-M", price: 62000, compareAtPrice: 72000, material: "White Gold", size: "7 inch", weight: "12.8g", stock: 10, productId: "prod-4", isActive: true },
    ],
    reviews: [],
    tags: ["white rose-gold", "bracelet", "diamond", "knot"],
    metaTitle: null,
    metaDescription: null,
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    isActive: true,
    averageRating: 4.6,
    reviewCount: 12,
    createdAt: new Date("2025-04-01"),
    updatedAt: new Date("2025-06-01"),
  },
  {
    id: "prod-5",
    name: "Soleil Diamond Pendant",
    slug: "soleil-diamond-pendant",
    description: "The Soleil pendant features a radiant sunburst design in 18K rose-gold, centered with a brilliant solitaire diamond. Its warm glow and geometric precision make it an everyday luxury piece.",
    shortDescription: "18K Gold sunburst diamond solitaire pendant",
    price: 34500,
    compareAtPrice: 39999,
    costPrice: 22000,
    sku: "LUM-PND-001",
    material: "Gold (18K)",
    weight: "5.6g",
    purity: "750",
    categoryId: "cat-5",
    images: [
      { id: "img-6", url: "", alt: "Soleil Diamond Pendant", position: 0, productId: "prod-5" },
    ],
    variants: [
      { id: "var-9", name: "With 16\" Chain", sku: "LUM-PND-001-16", price: 34500, compareAtPrice: 39999, material: "Gold (18K)", size: "16 inch chain", weight: "5.6g", stock: 9, productId: "prod-5", isActive: true },
      { id: "var-10", name: "With 18\" Chain", sku: "LUM-PND-001-18", price: 36500, compareAtPrice: 41999, material: "Gold (18K)", size: "18 inch chain", weight: "6.2g", stock: 11, productId: "prod-5", isActive: true },
    ],
    reviews: [],
    tags: ["rose-gold", "pendant", "diamond", "solitaire", "sunburst"],
    metaTitle: null,
    metaDescription: null,
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: true,
    isActive: true,
    averageRating: 4.9,
    reviewCount: 42,
    createdAt: new Date("2025-03-15"),
    updatedAt: new Date("2025-06-01"),
  },
  {
    id: "prod-6",
    name: "Heritage Kundan Bangles",
    slug: "heritage-kundan-bangles",
    description: "A pair of exquisite 22K rose-gold bangles featuring traditional Kundan work with uncut polki diamonds and vibrant enamel (meenakari). These heritage pieces blend centuries-old craftsmanship with contemporary elegance.",
    shortDescription: "22K Gold Kundan bangles set with meenakari work",
    price: 125000,
    compareAtPrice: null,
    costPrice: 92000,
    sku: "LUM-BNG-001",
    material: "Gold (22K)",
    weight: "42g",
    purity: "916",
    categoryId: "cat-6",
    images: [
      { id: "img-7", url: "", alt: "Heritage Kundan Bangles", position: 0, productId: "prod-6" },
    ],
    variants: [
      { id: "var-11", name: "Size 2.4", sku: "LUM-BNG-001-24", price: 125000, compareAtPrice: null, material: "Gold (22K)", size: "2.4", weight: "42g", stock: 3, productId: "prod-6", isActive: true },
      { id: "var-12", name: "Size 2.6", sku: "LUM-BNG-001-26", price: 125000, compareAtPrice: null, material: "Gold (22K)", size: "2.6", weight: "44g", stock: 5, productId: "prod-6", isActive: true },
    ],
    reviews: [],
    tags: ["rose-gold", "bangles", "kundan", "traditional", "wedding"],
    metaTitle: null,
    metaDescription: null,
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: false,
    isActive: true,
    averageRating: 5.0,
    reviewCount: 8,
    createdAt: new Date("2025-01-20"),
    updatedAt: new Date("2025-06-01"),
  },
  {
    id: "prod-7",
    name: "Luna Silver Anklet",
    slug: "luna-silver-anklet",
    description: "A dainty sterling silver anklet with crescent moon and star charms. The Luna anklet captures the magic of a moonlit night, with each charm delicately crafted and finished with a rhodium coating for lasting shine.",
    shortDescription: "925 Silver moon & star charm anklet",
    price: 3499,
    compareAtPrice: 4299,
    costPrice: 1800,
    sku: "LUM-ANK-001",
    material: "Silver (925)",
    weight: "8.2g",
    purity: "925",
    categoryId: "cat-1",
    images: [
      { id: "img-8", url: "", alt: "Luna Silver Anklet", position: 0, productId: "prod-7" },
    ],
    variants: [
      { id: "var-13", name: "9 inch", sku: "LUM-ANK-001-9", price: 3499, compareAtPrice: 4299, material: "Silver (925)", size: "9 inch", weight: "8.2g", stock: 25, productId: "prod-7", isActive: true },
      { id: "var-14", name: "10 inch", sku: "LUM-ANK-001-10", price: 3699, compareAtPrice: 4499, material: "Silver (925)", size: "10 inch", weight: "9.0g", stock: 20, productId: "prod-7", isActive: true },
    ],
    reviews: [],
    tags: ["silver", "anklet", "moon", "charm"],
    metaTitle: null,
    metaDescription: null,
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: true,
    isActive: true,
    averageRating: 4.5,
    reviewCount: 56,
    createdAt: new Date("2025-05-01"),
    updatedAt: new Date("2025-06-01"),
  },
  {
    id: "prod-8",
    name: "Majesty Platinum Ring",
    slug: "majesty-platinum-ring",
    description: "A commanding platinum ring featuring a princess-cut diamond center stone flanked by tapered baguettes. The Majesty ring represents the pinnacle of fine jewelry, crafted for those who appreciate uncompromising quality.",
    shortDescription: "Platinum princess-cut diamond ring with baguettes",
    price: 189000,
    compareAtPrice: 215000,
    costPrice: 145000,
    sku: "LUM-RNG-002",
    material: "Platinum",
    weight: "8.5g",
    purity: "950",
    categoryId: "cat-1",
    images: [
      { id: "img-9", url: "", alt: "Majesty Platinum Ring", position: 0, productId: "prod-8" },
    ],
    variants: [
      { id: "var-15", name: "Size 6", sku: "LUM-RNG-002-6", price: 189000, compareAtPrice: 215000, material: "Platinum", size: "6", weight: "8.2g", stock: 2, productId: "prod-8", isActive: true },
      { id: "var-16", name: "Size 7", sku: "LUM-RNG-002-7", price: 189000, compareAtPrice: 215000, material: "Platinum", size: "7", weight: "8.5g", stock: 3, productId: "prod-8", isActive: true },
    ],
    reviews: [],
    tags: ["platinum", "ring", "diamond", "princess", "luxury"],
    metaTitle: null,
    metaDescription: null,
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: false,
    isActive: true,
    averageRating: 5.0,
    reviewCount: 6,
    createdAt: new Date("2024-12-01"),
    updatedAt: new Date("2025-06-01"),
  },
];

export const sampleTestimonials = [
  {
    id: "test-1",
    name: "Priya Sharma",
    location: "Mumbai",
    rating: 5,
    text: "Absolutely stunning craftsmanship! The Celestial Ring exceeded all my expectations. The diamond sparkle is breathtaking, and the packaging felt like opening a treasure chest.",
    avatar: "PS",
    product: "Celestial Diamond Ring",
  },
  {
    id: "test-2",
    name: "Ananya Patel",
    location: "Delhi",
    rating: 5,
    text: "I ordered the Aria Necklace for my wedding, and it was the perfect statement piece. The filigree work is incredibly detailed — you can tell it's handcrafted with love.",
    avatar: "AP",
    product: "Aria Gold Necklace",
  },
  {
    id: "test-3",
    name: "Meera Krishnan",
    location: "Bangalore",
    rating: 5,
    text: "The Rose Petal Earrings are my everyday go-to now. They're lightweight, elegant, and I get compliments everywhere. Cherry Jewelry has won a customer for life!",
    avatar: "MK",
    product: "Rose Petal Earrings",
  },
  {
    id: "test-4",
    name: "Ritu Desai",
    location: "Ahmedabad",
    rating: 5,
    text: "Gifted the Heritage Kundan Bangles to my mother-in-law. She was in tears — the quality and traditional design took her back to her childhood. Priceless moment!",
    avatar: "RD",
    product: "Heritage Kundan Bangles",
  },
];
