// ============================================
// Cherry Jewelry — Product & Category Data Store
// ============================================

import type { Product, Category } from "@/types";

export const sampleCategories: Category[] = [
  {
    id: "cat-1",
    name: "Rings",
    slug: "rings",
    description: "Exquisite fashion rings & band sets",
    image: "/images/categories/rings.jpg",
    parentId: null,
    position: 1,
    isActive: true,
  },
  {
    id: "cat-2",
    name: "Necklaces",
    slug: "necklaces",
    description: "Stunning pendant necklaces & chains",
    image: "/images/categories/necklaces.jpg",
    parentId: null,
    position: 2,
    isActive: true,
  },
  {
    id: "cat-3",
    name: "Earrings",
    slug: "earrings",
    description: "Elegant studs, hoops & drop earrings",
    image: "/images/categories/earrings.jpg",
    parentId: null,
    position: 3,
    isActive: true,
  },
  {
    id: "cat-4",
    name: "Bracelets",
    slug: "bracelets",
    description: "Beautiful charm bracelets & bangles",
    image: "/images/categories/bracelets.jpg",
    parentId: null,
    position: 4,
    isActive: true,
  },
  {
    id: "cat-5",
    name: "Pendants",
    slug: "pendants",
    description: "Charming pendants & crystal amulets",
    image: "/images/categories/pendants.jpg",
    parentId: null,
    position: 5,
    isActive: true,
  },
  {
    id: "cat-6",
    name: "Bangles",
    slug: "bangles",
    description: "Fashion bangles with modern anti-tarnish finish",
    image: "/images/categories/bangles.jpg",
    parentId: null,
    position: 6,
    isActive: true,
  },
];

export const sampleProducts: Product[] = [
  {
    id: "nkc-001",
    name: "Rose Gold Plated Butterfly Wing Pendant Necklace with White Shell Inlay and Crystals for Women",
    slug: "rose-gold-plated-butterfly-wing-pendant-necklace-with-white-shell-inlay-and-crystals-for-women",
    description: "Exquisite rose gold plated butterfly wing pendant necklace featuring premium white shell inlay and sparkling AAA micro crystals. Handcrafted in durable anti-tarnish stainless steel for everyday luxury.",
    shortDescription: "Rose Gold Plated Butterfly Wing Pendant Necklace with White Shell Inlay and Crystals",
    price: 199,
    compareAtPrice: 290,
    costPrice: 80,
    sku: "NKC-001",
    material: "Stainless Steel",
    weight: "8.5g",
    purity: null,
    categoryId: "cat-2",
    category: {
      id: "cat-2",
      name: "Necklaces",
      slug: "necklaces",
      description: "Stunning necklaces that captivate",
      image: "/images/categories/necklaces.jpg",
      parentId: null,
      position: 2,
      isActive: true,
    },
    images: [
      { id: "img-nkc-1", url: "/placeholder.jpg", alt: "Rose Gold Plated Butterfly Wing Pendant Necklace", position: 0, productId: "nkc-001" },
    ],
    variants: [
      { id: "var-nkc-1", name: "Standard", sku: "NKC-001-STD", price: 199, compareAtPrice: 290, material: "Stainless Steel", size: null, weight: "8.5g", stock: 10, productId: "nkc-001", isActive: true },
    ],
    reviews: [],
    tags: ["fashion jewelry", "wholesale", "stainless steel", "rose gold", "butterfly", "pendant", "necklace"],
    metaTitle: "Rose Gold Butterfly Wing Pendant Necklace | Cherry Jewelry",
    metaDescription: "Shop the Rose Gold Plated Butterfly Wing Pendant Necklace with White Shell Inlay and Crystals.",
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: true,
    isActive: true,
    averageRating: 5.0,
    reviewCount: 18,
    createdAt: new Date("2026-08-01"),
    updatedAt: new Date("2026-08-01"),
  },
];

export const sampleTestimonials = [
  {
    id: "test-1",
    name: "Priya Sharma",
    location: "Mumbai",
    rating: 5,
    text: "Stunning quality and anti-tarnish finish! The Butterfly Wing Pendant Necklace exceeded all my expectations.",
    avatar: "PS",
    product: "Rose Gold Butterfly Pendant",
  },
  {
    id: "test-2",
    name: "Ananya Patel",
    location: "Delhi",
    rating: 5,
    text: "Great wholesale pricing and fast express shipping. Cherry Jewelry has become my main wholesale vendor for fashion jewelry!",
    avatar: "AP",
    product: "Rose Gold Necklace",
  },
  {
    id: "test-3",
    name: "Meera Krishnan",
    location: "Bangalore",
    rating: 5,
    text: "Lightweight, skin-friendly, and very elegant designs. Highly recommended for premium fashion jewelry.",
    avatar: "MK",
    product: "Fashion Pendant Set",
  },
];
